### PR TITLE
Adds integration with Appveyor

### PR DESCRIPTION
**Pull request by damianszczepanik**

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
I also use appveyor for some of my projects, but it is not clear what is missing here on the ci.jenkins.io side. @damianszczepanik could you please clarify? Do you plan any special integrations later?

**Comment by damianszczepanik** [comment]
What do you mean?

**Comment by oleg-nenashev** [comment]
TL;DR: What is the benefit of appveyor being compared to ci.jenkins.io ?

**Comment by damianszczepanik** [comment]
Except that Jenkins is sometimes busy - probably none but I like to have alternative

**Pull request merged**
